import assert from 'node:assert/strict';
import { mkdir, readFile } from 'node:fs/promises';
import path from 'node:path';
import { pathToFileURL } from 'node:url';
import { ROOT, TARGETS, writeJson } from './candidates.mjs';
import { createReviewWorkspaceServer } from '../review-workspace/server.mjs';
const { chromium } = await import(pathToFileURL(path.resolve(process.argv[2])).href);
const local='.local/codex/212/browser-canary';
await mkdir(path.join(ROOT,local),{recursive:true});
const workspace=await createReviewWorkspaceServer({port:0,stateRoot:path.join(ROOT,local,'state'),exportRoot:path.join(ROOT,local,'exports')});
const url=await workspace.start();
let browser;
const results=[], errors=[];
try {
    browser=await chromium.launch({channel:'chrome',headless:true,args:['--autoplay-policy=no-user-gesture-required']});
    const context=await browser.newContext({viewport:{width:1600,height:1100}});
    await context.route('**/*',route=>route.request().url().startsWith(`${url}/`)?route.continue():route.abort());
    context.on('page',p=>p.on('pageerror',e=>errors.push(e.message)));
    const page=await context.newPage();
    await page.goto(url);
    await page.waitForSelector('.candidate-button');
    assert.equal(await page.locator('#target option').count(),4);
    for(const id of TARGETS) {
        await page.locator('#target').selectOption(id);
        const candidates=workspace.data.candidatesByTarget.get(id);
        const regions=[];
        for(const [region,index] of [['early',0],['mid',Math.floor(candidates.length/2)],['late',candidates.length-1]]) {
            const candidate=candidates[index];
            await page.locator(`.candidate-button[data-id="${candidate.candidateWindowId}"]`).click();
            await page.waitForFunction(id=>document.querySelector('#candidate-heading h2')?.textContent===id,candidate.candidateWindowId);
            await page.waitForFunction(()=>[...document.querySelectorAll('#frames img')].length===3 && [...document.querySelectorAll('#frames img')].every(i=>i.complete&&i.naturalWidth>0));
            assert.equal(await page.locator('#legacy-audio').isVisible(),false);
            assert.equal(await page.locator('#scrim-context').isVisible(),true);
            assert.equal(await page.locator('#open-scrim').getAttribute('href'),candidate.scrimContextEvidence.url);
            await page.screenshot({path:path.join(ROOT,local,`${id}-${region}.png`),fullPage:true});
            regions.push({region,candidateWindowId:candidate.candidateWindowId,visualReady:true});
        }
        const candidate=candidates[Math.floor(candidates.length/2)];
        await page.locator(`.candidate-button[data-id="${candidate.candidateWindowId}"]`).click();
        await page.waitForFunction(id=>document.querySelector('#candidate-heading h2')?.textContent===id,candidate.candidateWindowId);
        const popupPromise=context.waitForEvent('page');
        await page.getByRole('link',{name:'Abrir no Player da Scrim',exact:true}).click();
        const popup=await popupPromise;
        await popup.waitForFunction(()=>window.scrimNavigationReady&&window.scrimSessionReady&&!window.scrimPlayer.syncing,null,{timeout:45000});
        const opened=await popup.evaluate(()=>({ ...window.scrimNavigationReady, sessionTarget:window.scrimPlayer.session.reviewTargetId, actualVodSeconds:window.scrimPlayer.video.currentTime, tracks:window.scrimPlayer.tracks.length }));
        assert.equal(opened.sessionTarget,id); assert.equal(opened.tracks,9);
        assert.ok(Math.abs(opened.actualVodSeconds-opened.seekVodSeconds)<0.1);
        await popup.getByRole('button',{name:'Reproduzir',exact:true}).click();
        await popup.waitForFunction(()=>window.scrimPlayer.status==='playing');
        await popup.waitForTimeout(2000);
        const playback=await popup.evaluate(()=>{
            const p=window.scrimPlayer, desired=(p.video.currentTime-p.session.syncModel.interceptSeconds)/p.session.syncModel.slope;
            return {error:p.error,activeTracks:p.tracks.filter(t=>p.active(t,desired)).length,playingTracks:p.tracks.filter(t=>!t.element.paused).length,videoTime:p.video.currentTime};
        });
        assert.equal(playback.error,null); assert.ok(playback.activeTracks>0); assert.equal(playback.playingTracks,playback.activeTracks); assert.ok(playback.videoTime>opened.actualVodSeconds+1);
        await popup.getByRole('checkbox',{name:'Solo track_03',exact:true}).check();
        assert.equal(await popup.evaluate(()=>window.scrimPlayer.mixer.tracks.filter(t=>window.scrimPlayer.mixer.gain(t.trackRef)>0).length),1);
        await popup.getByRole('checkbox',{name:'Solo track_03',exact:true}).uncheck();
        await popup.screenshot({path:path.join(ROOT,local,`${id}-scrim.png`),fullPage:true});
        await popup.close();
        await page.locator('[data-review-field="reviewNotes"]').fill('Synthetic technical canary only; not human semantic validation.');
        await page.locator('#review-state').selectOption('in_review');
        await page.locator('#segment-label').fill('synthetic technical segment');
        await page.locator('#add-segment').click();
        await page.locator('#save').click();
        await page.waitForFunction(()=>document.querySelector('#status').textContent==='Revisão salva localmente.');
        await page.locator('#export').click();
        await page.waitForFunction(()=>document.querySelector('#status').textContent==='Packet JSON e Markdown exportado localmente.');
        const packet=JSON.parse(await readFile(path.join(ROOT,local,'exports',id,'review_packet.json')));
        assert.equal(packet.candidates[0].candidateWindowId,candidate.candidateWindowId);
        assert.ok(packet.candidates[0].reviewSegments.length>=1); assert.ok(packet.candidates[0].scrimContextEvidence);
        await page.reload(); await page.locator('#target').selectOption(id);
        await page.locator(`.candidate-button[data-id="${candidate.candidateWindowId}"]`).click();
        await page.waitForFunction(()=>document.querySelector('#review-state').value==='in_review');
        assert.match(await page.locator('[data-review-field="reviewNotes"]').inputValue(),/Synthetic technical canary/);
        assert.ok(await page.locator('.segment-card').count()>=1);
        results.push({reviewTargetId:id,regions,scrimNavigation:opened,playback,mixerSoloVerified:true,stateSaveReopen:true,exportJsonMarkdown:true});
    }
    await page.locator('#target').selectOption('review_match_001');
    await page.locator('.candidate-button[data-id="review_match_001_window_0015"]').click();
    await page.waitForFunction(()=>document.querySelector('#candidate-heading h2')?.textContent==='review_match_001_window_0015');
    assert.equal(await page.locator('#legacy-audio').isVisible(),true);
    assert.equal(await page.locator('#scrim-context').isVisible(),false);
    assert.ok(await page.locator('.call-card').count()>0);
    await page.waitForFunction(()=>[...document.querySelectorAll('#frames img')].every(i=>i.complete&&i.naturalWidth>0));
    await page.screenshot({path:path.join(ROOT,local,'legacy-0015.png'),fullPage:true});
    assert.deepEqual(errors,[]);
    await writeJson(`${local}/result.json`,{technicalCanaryOnly:true,humanJudgmentClaimed:false,targets:results,legacy0015Ready:true,browserErrors:errors,existingHumanStateModified:false});
    console.log(JSON.stringify({targets:results,legacy0015Ready:true,browserErrors:errors},null,2));
} finally { await browser?.close(); await workspace.stop(); }
