import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { validateJsonSchema } from '../tools/lib/json-schema-validator.mjs';

const schema = JSON.parse(await readFile(new URL('../schemas/death-event-exposure-matched-lifecycle-evidence.schema.json', import.meta.url), 'utf8'));
const emptyFamily = { preStateContinuityStatus: 'insufficient_pre_state', forwardObserved: false, forwardDeltaSeconds: null, forwardPersistenceObserved: false, forwardPersistenceSampleCount: 0, inverseObserved: false, inverseDeltaSeconds: null, recoveryPersistenceObserved: false, recoveryPersistenceSampleCount: 0, completionDeltaSeconds: null, completeSameFamilyLifecycle: false, failureReason: 'pre_state_not_origin_continuous' };
const families = { healthBoundary: { ...emptyFamily }, booleanAlive: { ...emptyFamily }, respawnBoundary: { ...emptyFamily }, pawnLinkPresence: { ...emptyFamily } };
const horizonResults = [10, 20, 30, 60, 120, 180].map(horizonSeconds => ({ horizonSeconds, eligiblePairCount: 0, anchorCoherentLifecycleRate: 0, controlCoherentLifecycleRate: 0, pairedDifference: 0, pairedCensoringCount: 1 }));
const commonFollowUpDistribution = { lessThan10: 1, seconds10To19: 0, seconds20To29: 0, seconds30To59: 0, seconds60To119: 0, seconds120To179: 0, seconds180: 0 };
const perFamilyChainRates = { healthBoundary: { anchorCompleteRate: 0, controlCompleteRate: 0 }, booleanAlive: { anchorCompleteRate: 0, controlCompleteRate: 0 }, respawnBoundary: { anchorCompleteRate: 0, controlCompleteRate: 0 }, pawnLinkPresence: { anchorCompleteRate: 0, controlCompleteRate: 0 } };
const summary = { totalAnchors: 1, totalExactControls: 1, exactPairCount: 1, originConsistentPreStateCoverage: 0, commonFollowUpDistribution, perFamilyChainRates, analyzablePairCount: 0, anchorCoherentLifecycleRate: 0, controlCoherentLifecycleRate: 0, pairedDifference: 0, insufficientFollowUpPairs: 1, controlsTruncatedByRealAnchors: 1, anchorsTruncatedByNextAnchors: 1, booleanRespawnOnlyCoherentRate: 0, crossSurfaceSupportRate: 0, crossAnchorRecoveryCount: 0, contradictionCount: 0, ambiguityCount: 0, sourceReuseCount: 0, horizonResults, exposureMatchedAssessmentLevel: 'insufficient' };
const readiness = { originConsistentLifecycleEvidenceAvailable: true, exposureMatchedControlComparisonMeasurable: true, pairwiseLifecycleDiscriminationMeasurable: true, sourceTierCompositionMeasurable: true, candidateLevelExposureMatchedLifecycleConsumptionAvailable: true, readyForOperationalDeathFactPromotionReview: false, readyForFinalDeathFacts: false, readyForConfirmedWhoDied: false, readyForAttribution: false, readyForKillerVictim: false, readyForTeamfight: false, readyForGameplayInterpretation: false };
const artifact = { schemaVersion: 1, replayId: 'replay_010', artifactClass: 'death_event_exposure_matched_lifecycle_evidence', generatedBy: 'tools/emit-death-event-exposure-matched-lifecycle-evidence.mjs', generatedAt: 'task_189', rawDataCaptured: false, rawFieldNamesIncludedInRows: false, rawIdsIncluded: false, rawTicksIncluded: false, rawTimestampsIncluded: false, finalFactsProduced: false, attributionEmitted: false, anchorCount: 1, exactPairCount: 1, evidenceRowCount: 1, evidenceRows: [{ exposureMatchedLifecycleEvidenceKey: 'exposure_matched_lifecycle_000001', eventCandidateKey: 'death_event_candidate_000001', sourceTransitionKey: 'life_transition_000001', participantKey: 'participant_01', heroRefKey: 'hero_ref_01', teamRefKey: 'team_ref_01', anchorNormalizedElapsedSecond: 10, matchedControlNormalizedElapsedSecond: 30, anchorAvailableFollowUpSeconds: 5, controlAvailableFollowUpSeconds: 5, pairedCommonFollowUpSeconds: 5, followUpTruncationCause: 'equal_horizon', pairExposureStatus: 'insufficient_common_follow_up', anchorFamilies: families, controlFamilies: families, anchorCompleteFamilyCount: 0, controlCompleteFamilyCount: 0, anchorCoherentLifecycle: false, controlCoherentLifecycle: false, evidenceSourceTier: 'not_coherent', crossAnchorRecoveryObserved: false, contradictionObserved: false, ambiguousAssociation: false, lifecycleEvidenceClass: 'insufficient_common_follow_up', semanticStatus: 'unconfirmed_exposure_matched_lifecycle', finalFact: false }], summary, readiness, limitations: ['Unconfirmed candidate evidence only.'] };

test('exposure-matched lifecycle schema accepts a policy-safe paired row', () => assert.deepEqual(validateJsonSchema(schema, artifact).errors, []));
test('exposure-matched lifecycle schema rejects raw fields and final facts', () => { const unsafe = structuredClone(artifact); unsafe.evidenceRows[0].rawValue = 1; unsafe.evidenceRows[0].finalFact = true; assert.ok(validateJsonSchema(schema, unsafe).errors.length >= 2); });
