import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { validateJsonSchema } from '../tools/lib/json-schema-validator.mjs';

const schema = JSON.parse(await readFile(new URL('../schemas/death-event-segmented-lifecycle-evidence.schema.json', import.meta.url), 'utf8'));
const emptyFamily = { preStateStatus: 'insufficient_pre_state', forwardObserved: false, forwardDeltaSeconds: null, forwardPersistenceObserved: false, forwardPersistenceSampleCount: 0, inverseObserved: false, inverseDeltaSeconds: null, recoveryPersistenceObserved: false, recoveryPersistenceSampleCount: 0, completeSameFamilyLifecycle: false, failureReason: 'pre_state_unavailable' };
const families = { healthBoundary: { ...emptyFamily }, booleanAlive: { ...emptyFamily }, respawnBoundary: { ...emptyFamily }, pawnLinkPresence: { ...emptyFamily } };
const summary = { totalAnchors: 1, totalExactControls: 0, completeSameFamilyLifecycleRate: 0, atLeastTwoCompleteFamiliesRate: 0, coherentSegmentedLifecycleRate: 0, controlCoherentLifecycleRate: 0, anchorControlDifference: 0, crossAnchorRecoveryViolationCount: 0, crossFamilyAggregateOnlyCount: 0, opposingDirectionCount: 0, persistenceContradictionCount: 0, preStateStabilityCoverage: 0, forwardPersistenceCoverage: 0, recoveryPersistenceCoverage: 0, censoredFinalAnchorCount: 1, controlsCensoredByRealAnchors: 0, sequenceCountBridgeMismatches: 0, sourceReuseCount: 0, segmentedLifecycleAssessmentLevel: 'insufficient' };
const readiness = { sameFamilyLifecycleEvidenceAvailable: true, segmentedLifecycleConsistencyMeasurable: true, matchedControlLifecycleDiscriminationMeasurable: true, crossAnchorViolationsMeasurable: true, candidateLevelSegmentedLifecycleConsumptionAvailable: true, readyForOperationalDeathFactPromotionReview: false, readyForFinalDeathFacts: false, readyForConfirmedWhoDied: false, readyForAttribution: false, readyForKillerVictim: false, readyForTeamfight: false, readyForGameplayInterpretation: false };
const artifact = { schemaVersion: 1, replayId: 'replay_010', artifactClass: 'death_event_segmented_lifecycle_evidence', generatedBy: 'tools/emit-death-event-segmented-lifecycle-evidence.mjs', generatedAt: 'task_188', rawDataCaptured: false, rawFieldNamesIncludedInRows: false, rawIdsIncluded: false, rawTicksIncluded: false, rawTimestampsIncluded: false, finalFactsProduced: false, attributionEmitted: false, anchorCount: 1, controlCount: 0, evidenceRowCount: 1, evidenceRows: [{ segmentedLifecycleEvidenceKey: 'segmented_lifecycle_000001', eventCandidateKey: 'death_event_candidate_000001', sourceTransitionKey: 'life_transition_000001', participantKey: 'participant_01', heroRefKey: 'hero_ref_01', teamRefKey: 'team_ref_01', anchorNormalizedElapsedSecond: 10, nextAnchorNormalizedElapsedSecond: null, matchedControlNormalizedElapsedSecond: null, controlSegmentEndNormalizedSecond: null, anchorFamilies: families, completeSameFamilyLifecycleCount: 0, opposingExplicitDirectionObserved: false, ambiguousAssociation: false, persistenceContradictionObserved: false, anchorBoundaryViolationStatus: 'none', correctedRecoveryCompletionDeltaSeconds: null, matchedControlLifecycleResult: null, lifecycleEvidenceClass: 'insufficient_observation', semanticStatus: 'unconfirmed_segmented_lifecycle', finalFact: false }], summary, readiness, limitations: ['Unconfirmed candidate evidence only.'] };

test('segmented lifecycle schema accepts policy-safe same-family rows', () => assert.deepEqual(validateJsonSchema(schema, artifact).errors, []));
test('segmented lifecycle schema rejects raw fields and final facts', () => { const unsafe = structuredClone(artifact); unsafe.evidenceRows[0].rawValue = 1; unsafe.evidenceRows[0].finalFact = true; assert.ok(validateJsonSchema(schema, unsafe).errors.length >= 2); });
