import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, mkdir, readFile, readdir, writeFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { analyzeExposureCohort, buildExposurePairs, executePreparedExposureRun, horizonResults, prepareExposureMatchedRun } from '../tools/emit-death-event-exposure-matched-lifecycle-evidence.mjs';
import { PILOT_IDS } from '../tools/validate-task187-sequence-integrity.mjs';

const participantKey = 'participant_01';
function mapped(samples, events) { return { samples: new Map([[participantKey, samples]]), sampleIndexes: new Map([[participantKey, new Map(samples.map(row => [row.second, row.state]))]]), events: new Map([[participantKey, events]]) }; }
function base() { return { healthBoundary: 'positive', booleanAlive: true, respawnBoundary: 'non_positive', pawnLinkPresence: true }; }
function coherentMapped() {
    const normal = base(); const changed = { ...normal, healthBoundary: 'non_positive', booleanAlive: false }; const samples = [7, 8, 9].map(second => ({ second, state: { ...normal } })); samples.push({ second: 10, state: changed }, { second: 11, state: changed }, { second: 20, state: normal }, { second: 21, state: normal });
    const events = [{ key: 'h-f', family: 'healthBoundary', second: 10, direction: 'forward', toState: 'non_positive' }, { key: 'b-f', family: 'booleanAlive', second: 10, direction: 'forward', toState: false }, { key: 'h-i', family: 'healthBoundary', second: 20, direction: 'inverse', toState: 'positive' }, { key: 'b-i', family: 'booleanAlive', second: 20, direction: 'inverse', toState: true }]; return mapped(samples, events);
}
const reference = { participantKey, second: 10, key: 'anchor', commonFollowUpSeconds: 30, naturalBoundarySecond: 40 };

test('origin-consistent same-family chains complete only after recovery persistence', () => { const result = analyzeExposureCohort([reference], coherentMapped(), 'anchor').results.get('anchor'); assert.equal(result.completeCount, 2); assert.equal(result.coherent, true); assert.equal(result.families.healthBoundary.completionDeltaSeconds, 11); });
test('stable pre-state with the wrong forward origin cannot complete', () => { const input = coherentMapped(); for (const row of input.samples.get(participantKey).filter(row => row.second < 10)) row.state.healthBoundary = 'non_positive'; const result = analyzeExposureCohort([reference], input, 'anchor').results.get('anchor'); assert.equal(result.families.healthBoundary.preStateContinuityStatus, 'stable_wrong_forward_origin'); assert.equal(result.families.healthBoundary.completeSameFamilyLifecycle, false); });
test('an intervening state breaks continuity to the selected forward transition', () => { const normal = base(); const samples = [7, 8, 9].map(second => ({ second, state: { ...normal } })); samples.push({ second: 10, state: { ...normal, healthBoundary: 'non_positive' } }, { second: 11, state: normal }, { second: 12, state: { ...normal, healthBoundary: 'non_positive' } }, { second: 13, state: { ...normal, healthBoundary: 'non_positive' } }); const events = [{ key: 'h-f', family: 'healthBoundary', second: 12, direction: 'forward', toState: 'non_positive' }]; const result = analyzeExposureCohort([reference], mapped(samples, events), 'anchor').results.get('anchor'); assert.equal(result.families.healthBoundary.preStateContinuityStatus, 'intervening_transition_breaks_continuity'); assert.equal(result.families.healthBoundary.completeSameFamilyLifecycle, false); });

test('paired exposure uses the smaller anchor/control follow-up horizon', () => { const anchors = { candidates: [{ eventCandidateKey: 'death_event_candidate_000001', participantKey, normalizedElapsedSecond: 10 }, { eventCandidateKey: 'death_event_candidate_000002', participantKey, normalizedElapsedSecond: 40 }, { eventCandidateKey: 'death_event_candidate_000003', participantKey, normalizedElapsedSecond: 120 }] }; const controls = { evidenceRows: [{ eventCandidateKey: 'death_event_candidate_000001', controlNormalizedElapsedSecond: 100 }, { eventCandidateKey: 'death_event_candidate_000002', controlNormalizedElapsedSecond: 200 }, { eventCandidateKey: 'death_event_candidate_000003', controlNormalizedElapsedSecond: 250 }] }; const pair = buildExposurePairs(anchors, controls, 300)[0]; assert.equal(pair.anchorAvailable, 30); assert.equal(pair.controlAvailable, 20); assert.equal(pair.common, 20); assert.equal(pair.truncationCause, 'control_side'); });
test('multi-horizon rates use only pairs eligible for each horizon', () => { const empty = Object.fromEntries(['healthBoundary', 'booleanAlive', 'respawnBoundary', 'pawnLinkPresence'].map(family => [family, { completionDeltaSeconds: null }])); const complete = structuredClone(empty); complete.healthBoundary.completionDeltaSeconds = 8; complete.booleanAlive.completionDeltaSeconds = 9; const rows = [{ pairedCommonFollowUpSeconds: 10, anchorFamilies: complete, controlFamilies: empty, ambiguousAssociation: false, contradictionObserved: false, crossAnchorRecoveryObserved: false }, { pairedCommonFollowUpSeconds: 30, anchorFamilies: empty, controlFamilies: empty, ambiguousAssociation: false, contradictionObserved: false, crossAnchorRecoveryObserved: false }]; const horizons = horizonResults(rows); assert.equal(horizons[0].eligiblePairCount, 2); assert.equal(horizons[0].anchorCoherentLifecycleRate, 0.5); assert.equal(horizons[2].eligiblePairCount, 1); assert.equal(horizons[2].anchorCoherentLifecycleRate, 0); });

test('source mismatch blocks before replay path resolution', async () => { let resolved = 0; const manifest = { version: 1, runKind: 'task189-pilot', manifestIdentity: 'task189_exposure_matched_pilot_v1', replayIds: PILOT_IDS }; await assert.rejects(() => prepareExposureMatchedRun({ manifest, loadIntegrityGate: async () => ({ gate: 'task188_lifecycle_integrity_repaired', integrityStatus: 'passed', measurementStatus: 'completed', thresholdStatus: 'met', replayPathResolved: false, playerConstructed: false, createReadStreamCalled: false }), loadPilotGate: async () => ({}), sourceLoader: async replayId => ({ identity: { replayId }, transitions: {}, candidates: {}, controls: {}, historical: {} }), onReplayPathResolution: () => { resolved += 1; } })); assert.equal(resolved, 0); });
test('multi-replay failure publishes blocked metadata and preserves active bytes', async () => { const root = await mkdtemp(path.join(os.tmpdir(), 'task189-')); const activeRoot = path.join(root, 'active'); const blockedRoot = path.join(root, 'blocked'); await mkdir(activeRoot); await writeFile(path.join(activeRoot, 'marker.bin'), Buffer.from([1, 8, 9])); const before = await readFile(path.join(activeRoot, 'marker.bin')); const manifest = { runKind: 'task189-pilot', manifestIdentity: 'task189_exposure_matched_pilot_v1', replayIds: PILOT_IDS }; const plan = PILOT_IDS.map(replayId => ({ replayId })); let call = 0; const result = await executePreparedExposureRun({ manifest, plan, activeRoot, blockedRoot, replayExecutor: async input => { call += 1; return call === 2 ? { summary: { replayId: input.replayId, status: 'blocked', errorMessage: 'intentional' }, artifact: null } : { summary: { replayId: input.replayId, status: 'emitted' }, artifact: { replayId: input.replayId } }; } }); assert.equal(result.status, 'blocked'); assert.deepEqual(await readFile(path.join(activeRoot, 'marker.bin')), before); assert.deepEqual((await readdir(blockedRoot)).sort(), ['blocked-gate.json', 'blocked-summary.json', 'failure-audits.json']); });
