import test from 'node:test';
import assert from 'node:assert/strict';
import { BOUNDED_IDS, PILOT_IDS } from '../tools/validate-task187-sequence-integrity.mjs';
import { calculateAssignmentLedger, exactTask188CommitChecks, validateExactManifest, validateExactPilotGate, validateManifestSourcesBeforeReplay, validatePreOpenSources } from '../tools/validate-task188-lifecycle-integrity.mjs';

function sources() { const participant = { participantKey: 'participant_01', heroRefKey: 'hero_ref_01', teamRefKey: 'team_ref_01' }; const candidate = { eventCandidateKey: 'death_event_candidate_000001', sourceTransitionKey: 'life_transition_000001', participantKey: participant.participantKey, heroRefKey: participant.heroRefKey, teamRefKey: participant.teamRefKey, normalizedElapsedSecond: 10 }; return { identity: { replayId: 'replay_010', artifactClass: 'participant_identity', generatedAt: 'task_180', participantCount: 1, participants: [participant] }, transitions: { replayId: 'replay_010', artifactClass: 'life_state_transition_candidates', generatedAt: 'task_182', transitionCandidates: [{ transitionKey: candidate.sourceTransitionKey, participantKey: candidate.participantKey, normalizedElapsedSecond: 10, finalFact: false }], transitionCandidateSummary: { totalTransitionCandidates: 1 } }, candidates: { replayId: 'replay_010', artifactClass: 'death_event_candidates', generatedAt: 'task_183', candidateCount: 1, candidates: [candidate] }, controls: { replayId: 'replay_010', artifactClass: 'death_event_directional_discrimination_evidence', generatedAt: 'task_186', anchorCount: 1, matchedControlCount: 1, evidenceRowCount: 1, evidenceRows: [{ ...candidate, anchorNormalizedElapsedSecond: 10, controlSelectionStatus: 'selected', controlNormalizedElapsedSecond: 20, truthStatus: 'unconfirmed_candidate', finalFact: false }] }, historical: { replayId: 'replay_010', artifactClass: 'death_event_segmented_lifecycle_evidence', generatedAt: 'task_188', anchorCount: 1, controlCount: 1, evidenceRowCount: 1, evidenceRows: [{ ...candidate, anchorNormalizedElapsedSecond: 10, matchedControlNormalizedElapsedSecond: 20, semanticStatus: 'unconfirmed_segmented_lifecycle', finalFact: false }] } }; }

test('Task 188 commit belongs only to Task 188', () => { const checks = exactTask188CommitChecks({ tasks: [{ taskId: '188', commitSha: '58af2f44016e061fcbda140bc6928e0c4dc4970d' }] }, 'Commit: 58af2f44016e061fcbda140bc6928e0c4dc4970d', '## Task 188\nTask 188 commit: `58af2f44016e061fcbda140bc6928e0c4dc4970d`.'); assert.ok(Object.values(checks).every(Boolean)); });
test('full pre-open bridge accepts exact sources and rejects Task 182 mismatch', () => { const value = sources(); assert.equal(validatePreOpenSources('replay_010', value).integrityStatus, 'passed'); value.transitions.transitionCandidates[0].participantKey = 'participant_02'; assert.equal(validatePreOpenSources('replay_010', value).integrityStatus, 'failed'); });
test('Task 182 mismatch blocks before path, Player, and createReadStream hooks', async () => { let paths = 0; let players = 0; let streams = 0; const manifest = { version: 1, runKind: 'task189-pilot', manifestIdentity: 'task189_exposure_matched_pilot_v1', replayIds: PILOT_IDS }; await assert.rejects(() => validateManifestSourcesBeforeReplay(manifest, async replayId => { const value = sources(); value.identity.replayId = replayId; value.transitions.replayId = replayId; value.candidates.replayId = replayId; value.controls.replayId = replayId; value.historical.replayId = replayId; value.transitions.transitionCandidates[0].normalizedElapsedSecond = 11; return value; }).then(() => { paths += 1; players += 1; streams += 1; })); assert.deepEqual({ paths, players, streams }, { paths: 0, players: 0, streams: 0 }); });
test('assignment ledger calculates duplicate reuse and mutation fails integrity', () => { const row = { cohort: 'anchor', participantKey: 'participant_01', observationKey: 'observation_000001', referenceKey: 'death_event_candidate_000001', family: 'booleanAlive', stage: 'forward' }; assert.equal(calculateAssignmentLedger([row]).sourceReuseCount, 0); const mutated = calculateAssignmentLedger([row, { ...row, referenceKey: 'death_event_candidate_000002' }]); assert.equal(mutated.sourceReuseCount, 1); assert.equal(mutated.integrityStatus, 'failed'); });
test('exact manifests and pilot gate reject incomplete inputs', () => { assert.equal(validateExactManifest({ version: 1, runKind: 'task189-bounded32', manifestIdentity: 'task189_exposure_matched_bounded32_v1', replayIds: BOUNDED_IDS }), true); assert.throws(() => validateExactManifest({ version: 1, runKind: 'task189-bounded32', manifestIdentity: 'task189_exposure_matched_bounded32_v1', replayIds: [...BOUNDED_IDS, 'replay_037'] })); const gate = { gate: 'death_exposure_matched_lifecycle_pilot_ready', status: 'passed', manifestIdentity: 'task189_exposure_matched_pilot_v1', replayIds: PILOT_IDS, parserCompleted: 4, parserExpected: 4, anchorCount: 341, evidenceRowCount: 341, exactPairCount: 341, originConsistencyFieldsEmitted: true, commonFollowUpCalculatedCount: 341, horizonRateCount: 6, assignmentLedgerIntegrityStatus: 'passed', sourceReuseCount: 0, participantMappingFailures: 0, provenanceFailures: 0, bridgeFailures: 0, schemaFailures: 0, outputPolicyFailures: 0, protectedReplayAccessCount: 0, finalFacts: 0, attribution: 0, sizeGatePassed: true, allOrNothingGatePassed: true }; assert.doesNotThrow(() => validateExactPilotGate(gate)); for (const field of Object.keys(gate)) assert.throws(() => validateExactPilotGate({ ...gate, [field]: null }), field); });
